---
# handlers file for initramfs_network
#
# SPDX-FileCopyrightText: 2022 Risk.Ident GmbH <contact@riskident.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u

- name: Extract downloaded tarball
  block:
    - name: Cleanup previous files
      ansible.builtin.file:
        path: /opt/initramfs-tools-network-hook
        state: absent

      # We must extract the entire repository to ensure we include the LICENSE file
    - name: Unarchive git repo into /opt/initramfs-tools-network-hook
      ansible.builtin.unarchive:
        remote_src: true
        src: /opt/initramfs-tools-network-hook.tar.gz
        dest: /opt
        extra_opts: [
          # trim away leading "initramfs-tools-network-hook-${ git branch }/" prefix
          --transform, "s|initramfs-tools-network-hook-[^/]*/|initramfs-tools-network-hook/|",
          # skips root directory, and only extract files inside the dir
          --wildcards, "initramfs-tools-network-hook-*/*",
        ]
